name-template: "release-drafter-practice $NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
version-template: "$MAJOR.$MINOR.$PATCH"
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
template: |
  ## Changes

  $CHANGES
