on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.8
          - 3.9
          - 3.10

    steps:
      - name: Setup | Checkout the repository
        uses: actions/checkout@v3

      - name: Setup | Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Setup | Python dependencies
        run: |
          pip install '.[test]'

      - name: Test | pytest
        run: |
          pytest -v tests

  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.8
          - 3.9
          - 3.10

    steps:
      - name: Setup | Checkout the repository
        uses: actions/checkout@v3

      - name: Setup | Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Setup | Python dependencies
        run: |
          pip install '.[test]'

      - name: Test | black
        run: |
          black --check --diff src tests

      - name: Test | isort
        run: |
          isort **/*.py --check-only

      - name: Test | flake8
        run: |
          flake8 src tests
